# Generated by Django 2.2.7 on 2019-12-08 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartsalfa',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_salfa', to='api.Cart'),
        ),
        migrations.AlterField(
            model_name='cartsalfa',
            name='salfa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_salfa', to='api.Salfa'),
        ),
    ]
